name: Run Unit Test via Pytest  
  
on: [push]  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.12.2"]
  
    steps:  
      - uses: actions/checkout@v3  
      - name: Set up Python  3.12.2  
        uses: actions/setup-python@v4  
        with:  
          python-version:  3.12.2  
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  
#      - name: Lint with Ruff
#        run: |
#          pip install ruff
#          ruff --format=github --target-version=py310 .
        continue-on-error: true  
      - name: Test with pytest  
        run: |  
          pytest  -v -s
      - name: Generate Coverage Report  
        run: |  
          coverage report -m
